spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false

server:
  port: 8080

logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL:DEBUG


api:
  key: ${API_KEY}

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

Spring:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}