server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
api:
  key: ${API_KEY}

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#


