spring:
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
api:
  key: ${API_KEY}

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

logging:
  config: classpath:logback-spring-prod.xml

Spring:
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
